CREATE TABLE Clients(
    clients_id bigint GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL,
    name varchar(10),
    user_id bigint,
    PRIMARY KEY (clients_id)    
);

CREATE TABLE Machines(
    machines_id bigint GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL,
    machine_serviceable_id bigint,
    serial_number varchar(32),
    year int,
    times_repaired int,
    PRIMARY KEY (machines_id)
);

CREATE TABLE Machines_Serviceable(
    machines_serviceable_id bigint GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL,
    name varchar(50),
    trademark varchar(50),
    country varchar(50),
    country_ru varchar(50),
    available tinyint,
    PRIMARY KEY (machines_serviceable_id)
);

CREATE TABLE Orders(
    orders_id bigint GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL,
    client_id bigint,
    repair_type_id bigint,
    machine_id bigint,
    start date,
    status varchar(10),
    manager varchar(10),
    PRIMARY KEY (orders_id)
);

CREATE TABLE Repair_Types(
    repair_types_id bigint GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL,
    name varchar(10),
    name_ru varchar(10),
    price decimal(10,2),
    duration int,
    available tinyint,
    PRIMARY KEY (repair_types_id)
);

CREATE TABLE Users(
    users_id bigint GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL,
    login varchar(10),
    password varchar(64),
    password_text varchar(10),
    enabled tinyint,
    PRIMARY KEY (users_id)
);

CREATE TABLE User_Authorization(
    user_authorization_id bigint GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL,
    user_id bigint,
    role varchar(50),
    desc_en varchar(50),
    desc_ru varchar(50),
    PRIMARY KEY (user_authorization_id)
);