CREATE TABLE Clients(
    clients_id int GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL,
    name varchar(10),
    user_id int,
    PRIMARY KEY (clients_id)    
);

CREATE TABLE Machines(
    machines_id int GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL,
    machine_serviceable_id int,
    serial_number varchar(32),
    year int,
    times_repaired int,
    PRIMARY KEY (machines_id)
);

CREATE TABLE Machines_Serviceable(
    machines_serviceable_id int GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL,
    name varchar(50),
    trademark varchar(50),
    country varchar(50),
    PRIMARY KEY (machines_serviceable_id)
);

CREATE TABLE Orders(
    orders_id int GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL,
    client_id int,
    repair_type_id int,
    machine_id int,
    start date,
    status varchar(10),    
    PRIMARY KEY (orders_id)
);

CREATE TABLE Repair_Types(
    repair_types_id int GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL,
    name varchar(10),
    price decimal(10,2),
    duration int,
    PRIMARY KEY (repair_types_id)
);

CREATE TABLE Users(
    users_id int GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL,
    login varchar(10),
    password varchar(64),
    password_text varchar(10),
    PRIMARY KEY (users_id)
);

CREATE TABLE User_Authorization(
    user_authorization_id int GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL,
    user_id int,
    role varchar(50),
    PRIMARY KEY (user_authorization_id)
);